# Site settings
title: The Stable
email: asho@thestable.bg
description: > Our campers are fully equipped for your adventure. They are easy to drive, fast and capable brand new 4x4 machines. You can comfortably drive and sleep 4 people in the campervans. The VW California line has been iconic for almost 60 years, and that&#39;s why we think it is the best choice
baseurl: ""
url: "https://www.thestable.bg" 

twitter_username:
github_username:

# Build settings
markdown: kramdown
